services:
  app:
    build: ./app
    container_name: uwsgi
    volumes:
      - ./app:/app
      - ./app/data:/app/data
    user: "33:33"

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certs/server.crt:/etc/nginx/ssl/server.crt
      - ./certs/server.key:/etc/nginx/ssl/server.key
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - app
